### PR TITLE
Github actions

### PR DESCRIPTION
**Pull request by hannesa2**
advantage:
* faster
* easy to run Espresso tests, but in this repo there are no Espresso test, so I didn't run it

### CODE REVIEW

**Comment by hannesa2** [comment]
If you like it, you could remove Travis

**Comment by d4rken** [comment]
I like it, but I don't want to change it "just because", it would need to provide a specific benefit that we are currently missing.

Currently the CodeCoverage is broken again, would this fix it? Currently don't have time to investigate Travis again :grin:...

**Comment by hannesa2** [comment]
I only applied the same commands like in Travis. Broken or not, at least there is no error.

I at least move complete from Travis to Github actions because of the two reasons https://github.com/matomo-org/matomo-sdk-android/pull/293#issue-465407473

**Comment by d4rken** [comment]
Will fix this up on a different branch.

**Pull request merged**
