### PR TITLE
Create devcontainer.jsonhttps://github.com/matomo-org/matomo-sdk-andr…

### PR DESCRIPTION
**Pull request by Pruvitt86**
…oid.git

### CODE REVIEW

**Comment by hannesa2** [comment]
Please enlighten me: what's the purpose of this ?

**Comment by hannesa2** [comment]
@dependabot rebase

**Comment by d4rken** [comment]
Spam PR, imho. Amateur GitHub user or a bot.

**Comment by Pruvitt86** [comment]
> Spam PR, imho. Amateur GitHub user or a bot.

I'm new to all of this I'm trying to learn

**Pull request closed without merging**
