### PR TITLE
Update Gradle and verify version on CI

### PR DESCRIPTION
**Pull request by hannesa2**
* Update Gradle
* add output of Gradle task buildSetup->wrapper
* verify Gradle Version on CI

### CODE REVIEW

**Comment by hannesa2** [comment]
Github actions doesn't start, it looks like you have to enable it

image

**Comment by hannesa2** [comment]
This is how it looks like, when Github actions are enabled https://github.com/hannesa2/matomo-sdk-android/pull/2

image

**Comment by d4rken** [comment]
That's an awesome Github action, I had this exact concern in previous PRs :).

> Github actions doesn't start, it looks like you have to enable it

It's already enabled :thinking:

**Comment by hannesa2** [comment]
Now it seems to work !
I at least did a rebase to recent master, but I guess this is unrelated to the non-running-previous-action

**Comment by d4rken** [comment]
:ok_hand:

**Pull request merged**
