### PR TITLE
Changelog created by github

### PR DESCRIPTION
**Pull request by hannesa2**
https://github.com/softprops/action-gh-release/releases/tag/v0.1.14

Here you can see a sample https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta1

### CODE REVIEW

**Review by d4rken — APPROVED** [review]

**Comment by d4rken** [comment]
That looks really nice, cool ❤️ 

https://github.com/d4rken/android-starter-v4/releases/tag/v4.4.1

I love that it adds the little contributor icons to the bottom an mentions who authored a PR 🍻

**Comment by hannesa2** [comment]
This should here no more necessary 
image

Btw, I vote to remove the **_v_** from the git tag

**Comment by hannesa2** [comment]
Btw, you already tested it, please can you test it with `@v1` again ?

        uses: softprops/action-gh-release@v1

I'm not sure about the versioning there, and dependabot will make this pull request soon but the test needs to be done manually

**Comment by d4rken** [comment]
Looks okay with `@v1` too
https://github.com/d4rken/android-starter-v4/releases/tag/v4.4.1-rc1

**Pull request merged**
